### ISSUE TITLE
HttpRequestException handling

### ISSUE THREAD

**Issue by michaelfoster9** [scottoffen/fluenthttpclient#7]
Hello, I have been using this library and I love it. I have implemented some error handlers using your OnFailure methods.  That works great for failure responses returned from the server.  What is the strategy for handling HttpRequestExceptions which would get thrown, for example, if the users internet connection was down.

It would be nice to be able to hande that within this framework.  Please let me know if there is a way to do that, or if that is a possible future feature.

**Comment by scottoffen** [comment]
Yep, this can be done.

- I've added `Action<HttpRequestException> HttpRequestExceptionHandler` to the `HttpRequestBuilder` class.

- I updated the send method to catch the exception and, if an action has been defined, it will pass that exception to the action and then return null. If that action hasn't been defined, it will rethrow the exception. You can always rethrow the exception in the handler if you want to.

- I added the extension method `OnHttpRequestException` that will allow the action to be defined using the same fluent syntax that is the core of this library.

All this will be in the v3.0 release.

**Comment by scottoffen** [comment]
This has been deprecated in version 4 in favor of using a more comprehensive tool such as [Polly](https://github.com/App-vNext/Polly).
